### ISSUE TITLE
Web Interface crashes when clicking on certain buttons 

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#189] opened 2016-03-14 18:03 UTC
Hi Frédéric,

I have some issue using web interface. At the moment, clicking Host > create button without entering any value results in 400 bad status error code.

![image](https://cloud.githubusercontent.com/assets/9393789/13754289/b6a889e8-ea16-11e5-92ac-bef343d226fc.png)

here the trace output: 
<pre><code>
14/03/2016/18:49:13.156 DEBUG [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-13] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.channelRead0(HttpResponsiveSslHandler.java:2047) : Msg: /Hosts.html
14/03/2016/18:49:13.156 DEBUG [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-13] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.checkSession(HttpResponsiveSslHandler.java:2174) : Found i18next: i18next=en
14/03/2016/18:49:13.156 DEBUG [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-13] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.checkSession(HttpResponsiveSslHandler.java:2153) : Found session: R66SESSIONcovrnlwaarpmgr=covrnlwaarpmgr3c4e17e6b18119c3
14/03/2016/18:49:13.157 ERROR [org.waarp.openr66.protocol.exception.OpenR66ExceptionTrappedFactory] [HttpWorker-13] org.waarp.openr66.protocol.exception.OpenR66ExceptionTrappedFactory.getExceptionFromTrappedException(OpenR66ExceptionTrappedFactory.java:134) : Null pointer Exception
java.lang.NullPointerException: null
        at org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.Hosts(HttpResponsiveSslHandler.java:901) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.channelRead0(HttpResponsiveSslHandler.java:2099) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.channelRead0(HttpResponsiveSslHandler.java:109) ~[WaarpR66-3.0.5.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1110) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:968) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:349) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
14/03/2016/18:49:13.158 WARN [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-13] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.exceptionCaught(HttpResponsiveSslHandler.java:2307) : Exception in HttpSslHandler Null Pointer Exception
14/03/2016/18:49:13.158 DEBUG [org.waarp.common.state.MachineState] [HttpWorker-13] org.waarp.common.state.MachineState.setAsFinal(MachineState.java:167) : New State: CLOSEDCHANNEL from OPENEDCHANNEL
14/03/2016/18:49:13.158 WARN [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-13] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.exceptionCaught(HttpResponsiveSslHandler.java:2307) : Exception in HttpSslHandler Null Pointer Exception
14/03/2016/18:49:13.158 DEBUG [org.waarp.common.state.MachineState] [HttpWorker-13] org.waarp.common.state.MachineState.setAsFinal(MachineState.java:167) : New State: CLOSEDCHANNEL from OPENEDCHANNEL
14/03/2016/18:49:13.259 DEBUG [org.waarp.common.database.DbSession] [HttpWorker-13] org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:353) : DbConnection still in use: 0
14/03/2016/18:49:13.259 DEBUG [org.waarp.common.database.DbSession] [HttpWorker-13] org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:358) : Fore close Db Conn: AMpasUAZZQBQVoASygABU3Y-wlI=
14/03/2016/18:49:13.261 INFO [org.waarp.common.database.DbSession] [HttpWorker-13] org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:369) : Current cached connection: 10
14/03/2016/18:49:13.262 DEBUG [org.waarp.common.crypto.ssl.WaarpSslUtility] [SSLTHREAD_Thread-648] org.waarp.common.crypto.ssl.WaarpSslUtility.removingSslHandler(WaarpSslUtility.java:215) : Found SslHandler and wait for Ssl.close() : [id: 0x3bb2031d, /127.0.0.1:46503 => /127.0.0.1:8067]
14/03/2016/18:49:13.263 DEBUG [org.waarp.common.crypto.ssl.WaarpSslUtility] [SSLTHREAD_Thread-648] org.waarp.common.crypto.ssl.WaarpSslUtility.closingSslChannel(WaarpSslUtility.java:175) : Close the channel and returns the ChannelFuture: [id: 0x3bb2031d, /127.0.0.1:46503 => /127.0.0.1:8067]
14/03/2016/18:49:13.265 DEBUG [org.waarp.common.crypto.ssl.WaarpSslUtility] [HttpWorker-13] org.waarp.common.crypto.ssl.WaarpSslUtility$3.operationComplete(WaarpSslUtility.java:218) : Ssl closed: [id: 0x3bb2031d, /127.0.0.1:46503 => /127.0.0.1:8067]
14/03/2016/18:49:13.387 DEBUG [org.waarp.common.crypto.ssl.WaarpSslContextFactory] [HttpWorker-14] org.waarp.common.crypto.ssl.WaarpSslContextFactory.initInitializer(WaarpSslContextFactory.java:209) : Has TrustManager? false Is ServerMode? true
14/03/2016/18:49:13.387 DEBUG [org.waarp.common.crypto.ssl.WaarpSslHandler] [HttpWorker-14] org.waarp.common.crypto.ssl.WaarpSslHandler.handlerAdded(WaarpSslHandler.java:50) : Ssl Handler added: [id: 0xc60725f7, /127.0.0.1:46504 => /127.0.0.1:8067]
14/03/2016/18:49:13.391 DEBUG [io.netty.handler.ssl.SslHandler] [HttpWorker-14] [id: 0xc60725f7, /127.0.0.1:46504 => /127.0.0.1:8067] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
14/03/2016/18:49:13.396 DEBUG [org.waarp.common.crypto.ssl.WaarpSslContextFactory] [HttpWorker-15] org.waarp.common.crypto.ssl.WaarpSslContextFactory.initInitializer(WaarpSslContextFactory.java:209) : Has TrustManager? false Is ServerMode? true
14/03/2016/18:49:13.397 DEBUG [org.waarp.common.crypto.ssl.WaarpSslHandler] [HttpWorker-15] org.waarp.common.crypto.ssl.WaarpSslHandler.handlerAdded(WaarpSslHandler.java:50) : Ssl Handler added: [id: 0x6ef5258a, /127.0.0.1:46505 => /127.0.0.1:8067]
14/03/2016/18:49:13.420 DEBUG [io.netty.handler.ssl.SslHandler] [HttpWorker-15] [id: 0x6ef5258a, /127.0.0.1:46505 => /127.0.0.1:8067] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
14/03/2016/18:49:13.422 DEBUG [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-15] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.channelRead0(HttpResponsiveSslHandler.java:2047) : Msg: /favicon.ico
</code></pre>

Same thing happens when clicking on restart button in the TRANSFERS > CANCEL-START menu.
The trace is nearly the same.
<pre><code>
14/03/2016/18:55:20.630 DEBUG [org.waarp.openr66.protocol.networkhandler.NetworkTransaction] [HttpWorker-43] org.waarp.openr66.protocol.networkhandler.NetworkTransaction.createConnection(NetworkTransaction.java:352) : Constraints NOT exceeded
14/03/2016/18:55:20.631 ERROR [org.waarp.openr66.protocol.exception.OpenR66ExceptionTrappedFactory] [HttpWorker-43] org.waarp.openr66.protocol.exception.OpenR66ExceptionTrappedFactory.getExceptionFromTrappedException(OpenR66ExceptionTrappedFactory.java:134) : Null pointer Exception
java.lang.NullPointerException: null
        at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.getBlacklistNCR(NetworkTransaction.java:244) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.getRemoteChannel(NetworkTransaction.java:1057) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.createNewConnection(NetworkTransaction.java:416) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.createConnection(NetworkTransaction.java:365) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.createConnectionWithRetry(NetworkTransaction.java:295) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.client.RequestTransfer.sendValid(RequestTransfer.java:461) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.client.RequestTransfer.run(RequestTransfer.java:330) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.utils.TransferUtils.restartTransfer(TransferUtils.java:112) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.CancelRestart(HttpResponsiveSslHandler.java:701) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.channelRead0(HttpResponsiveSslHandler.java:2085) ~[WaarpR66-3.0.5.jar:na]
        at org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.channelRead0(HttpResponsiveSslHandler.java:109) ~[WaarpR66-3.0.5.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1110) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:968) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:349) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-all-4.1.0.Beta7.jar:4.1.0.Beta7]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
14/03/2016/18:55:20.632 WARN [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-43] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.exceptionCaught(HttpResponsiveSslHandler.java:2307) : Exception in HttpSslHandler Null Pointer Exception
14/03/2016/18:55:20.632 WARN [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-43] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.exceptionCaught(HttpResponsiveSslHandler.java:2307) : Exception in HttpSslHandler Null Pointer Exception
14/03/2016/18:55:20.633 DEBUG [org.waarp.common.state.MachineState] [HttpWorker-43] org.waarp.common.state.MachineState.setAsFinal(MachineState.java:167) : New State: CLOSEDCHANNEL from OPENEDCHANNEL
14/03/2016/18:55:20.733 DEBUG [org.waarp.common.database.DbSession] [HttpWorker-43] org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:353) : DbConnection still in use: 0
14/03/2016/18:55:20.733 DEBUG [org.waarp.common.database.DbSession] [HttpWorker-43] org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:358) : Fore close Db Conn: ACO2YUAZZQBQVoASygABU3ZEe_Q=
14/03/2016/18:55:20.735 INFO [org.waarp.common.database.DbSession] [HttpWorker-43] org.waarp.common.database.DbSession.forceDisconnect(DbSession.java:369) : Current cached connection: 10
14/03/2016/18:55:20.736 DEBUG [org.waarp.common.crypto.ssl.WaarpSslUtility] [SSLTHREAD_Thread-656] org.waarp.common.crypto.ssl.WaarpSslUtility.removingSslHandler(WaarpSslUtility.java:215) : Found SslHandler and wait for Ssl.close() : [id: 0x2d11f028, /127.0.0.1:46534 => /127.0.0.1:8067]
14/03/2016/18:55:20.736 DEBUG [org.waarp.common.crypto.ssl.WaarpSslUtility] [SSLTHREAD_Thread-656] org.waarp.common.crypto.ssl.WaarpSslUtility.closingSslChannel(WaarpSslUtility.java:175) : Close the channel and returns the ChannelFuture: [id: 0x2d11f028, /127.0.0.1:46534 => /127.0.0.1:8067]
14/03/2016/18:55:20.737 DEBUG [org.waarp.common.crypto.ssl.WaarpSslUtility] [HttpWorker-43] org.waarp.common.crypto.ssl.WaarpSslUtility$3.operationComplete(WaarpSslUtility.java:218) : Ssl closed: [id: 0x2d11f028, /127.0.0.1:46534 => /127.0.0.1:8067]
14/03/2016/18:55:20.879 DEBUG [org.waarp.common.crypto.ssl.WaarpSslContextFactory] [HttpWorker-44] org.waarp.common.crypto.ssl.WaarpSslContextFactory.initInitializer(WaarpSslContextFactory.java:209) : Has TrustManager? false Is ServerMode? true
14/03/2016/18:55:20.880 DEBUG [org.waarp.common.crypto.ssl.WaarpSslHandler] [HttpWorker-44] org.waarp.common.crypto.ssl.WaarpSslHandler.handlerAdded(WaarpSslHandler.java:50) : Ssl Handler added: [id: 0x585bc11a, /127.0.0.1:46535 => /127.0.0.1:8067]
14/03/2016/18:55:20.886 DEBUG [io.netty.handler.ssl.SslHandler] [HttpWorker-44] [id: 0x585bc11a, /127.0.0.1:46535 => /127.0.0.1:8067] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
14/03/2016/18:55:20.890 DEBUG [org.waarp.common.crypto.ssl.WaarpSslContextFactory] [HttpWorker-45] org.waarp.common.crypto.ssl.WaarpSslContextFactory.initInitializer(WaarpSslContextFactory.java:209) : Has TrustManager? false Is ServerMode? true
14/03/2016/18:55:20.891 DEBUG [org.waarp.common.crypto.ssl.WaarpSslHandler] [HttpWorker-45] org.waarp.common.crypto.ssl.WaarpSslHandler.handlerAdded(WaarpSslHandler.java:50) : Ssl Handler added: [id: 0x9a93a19a, /127.0.0.1:46536 => /127.0.0.1:8067]
14/03/2016/18:55:20.913 DEBUG [io.netty.handler.ssl.SslHandler] [HttpWorker-45] [id: 0x9a93a19a, /127.0.0.1:46536 => /127.0.0.1:8067] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
14/03/2016/18:55:20.915 DEBUG [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-45] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.channelRead0(HttpResponsiveSslHandler.java:2047) : Msg: /favicon.ico
</code></pre>

Regards

**Comment by fredericBregier** [comment] 2016-03-14 20:26
For the first, even if it is a bug (null value should be checked), what else could you expect by clicking create without any value?

On the second, if the condition is similar, same thing. But I'm not sure since you did not described the condition.

We will fix those issues of course !

**Comment by alexbarta** [comment] 2016-03-15 09:51
In the second case, I was just clicking on restart button for a specific transfer.

Thank you!

**Comment by fredericBregier** [comment] 2016-03-16 17:19
To be honnest, I can't reproduce yet the second error, but maybe the initial fix may fix the second one... You may try later on again once the fix will be merged and published.
So I keep this issue open.

**Comment by fredericBregier** [comment] 2016-04-04 21:07
New version published! ;-)
So I close this one. Feel free to open a new one it if an issue is still there.

**Closed by fredericBregier** 2016-04-04 21:07 UTC
