### ISSUE TITLE
R66 windows client GUI freezes on transfer error

### ISSUE THREAD

**Issue by alexbarta** [waarp/WaarpR66#193] opened 2016-03-21 10:02 UTC
Hi Frédéric,

I'm trying to use R66Cl.bat, but when ERROR transfer appears, the only thing I can do is to relaunch the batch file.

A small screen of what happens:
![image](https://cloud.githubusercontent.com/assets/9393789/13915152/27075e08-ef53-11e5-91be-75e03bd1df59.png)

From DOS output I don't see any evident error..

ps. A question... Am I allowed to send a file that is located outside the "out" folder ? Or do I need always to put that file in "out" folder and then send it via GUI/command line?

Thanks you in advance!

**Comment by alexbarta** [comment] 2016-03-21 10:06
sorry, here the ERROR that appears in the GUI

<pre><code>
21/03/2016/10:47:40.898 ERROR [org.waarp.openr66.protocol.localhandler.TransferActions] [LocalWorker-4] org.waarp.openr66.protocol.localhandler.TransferActions.request(TransferActions.java:398) : Bad runner at startup RequestPacket: rule3 : 1 : file:/C:/MFT/waarp/out/prova.txt :  : 4096 : 0 : 1 : u : 23 Session: FS[ERROR] (TransferActions.java:157):99  Auth:true HostAuth: covrnlwaarpmgr address: covrnlwaarpmgr:6667 isSSL: true admin: true isClient: false isActive: true isProxified: true (32) Version: 3.0.5.{"HOSTID":"covrnlwaarpmgr","VERSION":"3.0.5","FILESIZE":true,"FINALHASH":true,"DIGESTALGO":"SHA-1","PROXIFIED":true,"SEPARATOR":";"} [ READONLY TRANSFER RULE HOST LIMIT SYSTEM LOGCONTROL PARTNER CONFIGADMIN FULLADMIN ]     Dir: /     no File     &ltRULE&gtrule3&lt/RULE&gt&ltID&gt1267826556387088876&lt/ID&gt&ltFILE&gtfile:/C:/MFT/waarp/out/prova.txt&lt/FILE&gt     &ltSTEP&gtNOTASK(NOTASK):-1:Unknown status&lt/STEP&gt&ltRANK&gt0&lt/RANK&gt&ltBLOCKSIZE&gt4096&lt/BLOCKSIZE&gt     &ltSENDER&gttrue&lt/SENDER&gt&ltMOVED&gtfalse&lt/MOVED&gt&ltMODE&gtSENDMODE&lt/MODE&gt     &ltREQR&gtpmttoam11g&lt/REQR&gt&ltREQD&gtcovrnlwaarpmgr&lt/REQD&gt     &ltSTART&gt2016-03-21 10:47:40.896&lt/START&gt&ltSTOP&gt2016-03-21 10:47:40.896&lt/STOP&gt     &ltINTERNAL&gtRUNNING : Unknown status&lt/INTERNAL&gt&ltORIGINALSIZE&gt23&lt/ORIGINALSIZE&gt     &ltFILEINFO&gt&lt/FILEINFO&gt &ltTRANSFERINFO&gt{"ORIGINALSIZE":23}&lt/TRANSFERINFO&gt
21/03/2016/10:47:41.000 ERROR [org.waarp.openr66.protocol.localhandler.ConnectionActions] [LocalWorker-4] org.waarp.openr66.protocol.localhandler.ConnectionActions.errorMesg(ConnectionActions.java:555) : 71ffef14: ErrorPacket:(3:u) Not known remote asked query
21/03/2016/10:47:41.025 ERROR [org.waarp.openr66.database.data.DbTaskRunner] [LocalWorker-4] org.waarp.openr66.database.data.DbTaskRunner.errorTransfer(DbTaskRunner.java:3430) : Transfer KO on null due to Pre task in error (or even before)
21/03/2016/10:47:41.049 WARN [org.waarp.openr66.context.task.LogTask] [LocalWorker-4] org.waarp.common.logging.AbstractWaarpLogger.log(AbstractWaarpLogger.java:146) : erreur SEND #Pre task in error (or even before)#     Session: FS[ERROR] (ConnectionActions.java:556):46  Auth:true HostAuth: covrnlwaarpmgr address: covrnlwaarpmgr:6667 isSSL: true admin: true isClient: false isActive: true isProxified: true (32) Version: 3.0.5.{"HOSTID":"covrnlwaarpmgr","VERSION":"3.0.5","FILESIZE":true,"FINALHASH":true,"DIGESTALGO":"SHA-1","PROXIFIED":true,"SEPARATOR":";"} [ READONLY TRANSFER RULE HOST LIMIT SYSTEM LOGCONTROL PARTNER CONFIGADMIN FULLADMIN ]     Dir: /     no File     &ltRULE&gtrule3&lt/RULE&gt&ltID&gt1267826556387088876&lt/ID&gt&ltFILE&gtfile:/C:/MFT/waarp/out/prova.txt&lt/FILE&gt     &ltSTEP&gtERRORTASK(NOTASK):0:Current step in running&lt/STEP&gt&ltRANK&gt0&lt/RANK&gt&ltBLOCKSIZE&gt4096&lt/BLOCKSIZE&gt     &ltSENDER&gttrue&lt/SENDER&gt&ltMOVED&gtfalse&lt/MOVED&gt&ltMODE&gtSENDMODE&lt/MODE&gt     &ltREQR&gtpmttoam11g&lt/REQR&gt&ltREQD&gtcovrnlwaarpmgr&lt/REQD&gt     &ltSTART&gt2016-03-21 10:47:40.896&lt/START&gt&ltSTOP&gt2016-03-21 10:47:40.896&lt/STOP&gt     &ltINTERNAL&gtINERROR : Not known remote asked query&lt/INTERNAL&gt&ltORIGINALSIZE&gt23&lt/ORIGINALSIZE&gt     &ltFILEINFO&gt&lt/FILEINFO&gt &ltTRANSFERINFO&gt{"ORIGINALSIZE":23}&lt/TRANSFERINFO&gt
</pre></code>

**Comment by fredericBregier** [comment] 2016-03-21 19:45
@alexbarta According to the log, it seems the remote host is unknown from the local client. You shall have at least a XML file for authentification part (see https://waarp.github.io/Waarp/R66AuthentConfig.html ) that is linked into the main configuration using the field identity/authentfile.

On the freeze, it should not exceed 3 x time out connection parameter in this case (limit/timeoutcon which is by default set to 30s so at most 1.5 minute). You might decrease this number in the configuration file (for instance 5s) for GUI client, since 30s is really only adapted for server part.

Hoping this helps you

**Comment by alexbarta** [comment] 2016-03-22 10:04
Ok thanks I'll let you know asap..

**Comment by alexbarta** [comment] 2016-03-23 12:14
Well in authent xml file the host is listed, because when I send a file through r66syncsend command from same machine I am able to do it without problems. 

An exception I see know when sending a file from client gui:
<pre><code>
23/03/2016/12:00:16.437 INFO [org.waarp.openr66.protocol.configuration.Configuration] [AWT-EventQueue-0] org.waarp.openr66
.protocol.configuration.Configuration.pipelineInit(Configuration.java:668) : Current launched threads: 11
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0
        at javax.swing.text.BoxView.getOffset(BoxView.java:1101)
        at javax.swing.text.BoxView.childAllocation(BoxView.java:695)
        at javax.swing.text.CompositeView.getChildAllocation(CompositeView.java:232)
        at javax.swing.text.BoxView.getChildAllocation(BoxView.java:453)
        at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.calculateViewPosition(BasicTextUI.java:1991)
        at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.layoutContainer(BasicTextUI.java:1967)
        at java.awt.Container.layout(Container.java:1503)
        at java.awt.Container.doLayout(Container.java:1492)
        at java.awt.Container.validateTree(Container.java:1688)
        at java.awt.Container.validateTree(Container.java:1697)
        at java.awt.Container.validateTree(Container.java:1697)
        at java.awt.Container.validateTree(Container.java:1697)
        at java.awt.Container.validateTree(Container.java:1697)
        at java.awt.Container.validateTree(Container.java:1697)
        at java.awt.Container.validate(Container.java:1623)
        at javax.swing.RepaintManager$2.run(RepaintManager.java:691)
        at javax.swing.RepaintManager$2.run(RepaintManager.java:689)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:688)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1676)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:699)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
</pre></code>

To be honest I have no idea of why my transfer fails, apart the exception reported above.

**Comment by fredericBregier** [comment] 2016-03-24 07:24
That's the issue of awt: I cannot either know where is the issue...
I'm missing information.
Once in the GUI, can you "ping" the host ? (Verify the connexion)
Until now, I cannot reproduce the error (I tried both cases remote server up or down).

**Comment by alexbarta** [comment] 2016-03-24 14:45
Yes I confirm I can telnet R66Server target on port 6667 from client DOS..

Well I made some improvement.. I was able to send a file only when information field in the client GUI was NOT empty, otherwise the same file transfer fails. When client fails, even lowering timeout configuration, doesn't unfreeze.  Could you please check that?

**Comment by fredericBregier** [comment] 2016-03-24 20:28
Strange. I'm not able to reproduce the exact same issue.
Whatever the field information is filled or not, the transfer is done correctly.
I'm able to get the GUI frozen on one special item: when the rule is not allowed for the client and therefore refused by the server (I need to check why yet).
But if it cannot reach the server (so no connection at all), it freezes until the timeout is over and I get the control back.

Note however that even if this GUI is published, we feel like it is more a "sample" than a real production tool (as you see, even me, sometime I have some special kind of issue). In most cases, this kind of GUI is "rebuild", inspiring from the example, within the user final application.

We might focus more on this tool later on. Of course, if we can fix any issue, we will do for sure.
Right now, except my error (not the same as yours), I cannot fix your issue since I cannot reproduce it...
Don't know what to say...

**Comment by fredericBregier** [comment] 2016-04-04 21:08
You may try the last version. Since I was not able to reproduce your error, I cannot guarantee that it is fixed yet.

**Comment by fredericBregier** [comment] 2016-05-15 16:44
Could you confirm?

**Comment by bcarlin** [comment] 2017-03-08 14:32
Any news on that ?

**Comment by bcarlin** [comment] 2017-03-22 16:59
No feedback... I'm closing the issue

**Closed by bcarlin** 2017-03-22 16:59 UTC
